// TODO: It will be implemented in the future because there is no Hijri converter to Jalali and vice versa into the Project yet
export const lunarEvents = [
  {
    day: '7/1',
    title: 'ولادت امام محمد باقر علیه السلام',
    holiday: false,
    isLunar: true,
  },
  {
    day: '7/3',
    title: 'شهادت امام علی النقی الهادی علیه السلام',
    holiday: false,
    isLunar: true,
  },
  {
    day: '7/10',
    title: 'ولادت امام محمد تقی علیه السلام',
    holiday: false,
    isLunar: true,
  },
  {
    day: '7/13',
    title: 'ولادت امام علی علیه السلام و روز پدر',
    holiday: true,
    isLunar: true,
  },
  {
    day: '7/15',
    title: 'وفات حضرت زینب سلام الله علیها',
    holiday: false,
    isLunar: true,
  },
  {
    day: '7/25',
    title: 'شهادت امام موسی کاظم علیه السلام',
    holiday: false,
    isLunar: true,
  },
  { day: '7/27', title: 'مبعث رسول اکرم', holiday: true, isLunar: true },
  {
    day: '8/3',
    title: 'ولادت سالار شهیدان، امام حسین علیه السلام',
    holiday: false,
    isLunar: true,
  },
  {
    day: '8/4',
    title: 'ولادت ابوالفضل العباس علیه السلام',
    holiday: false,
    isLunar: true,
  },
  {
    day: '8/5',
    title: 'ولادت امام زین العابدین علیه السلام',
    holiday: false,
    isLunar: true,
  },
  {
    day: '8/11',
    title: 'ولادت علی اکبر علیه السلام و روز جوان',
    holiday: false,
    isLunar: true,
  },
  {
    day: '8/15',
    title: 'ولادت حضرت قائم عجل الله تعالی فرجه و جشن نیمه شعبان',
    holiday: false,
    isLunar: true,
  },
  {
    day: '9/15',
    title: 'ولادت امام حسن مجتبی علیه السلام',
    holiday: false,
    isLunar: true,
  },
  { day: '9/18', title: 'شب قدر', holiday: false, isLunar: true },
  {
    day: '9/19',
    title: 'ضربت خوردن حضرت علی علیه السلام',
    holiday: false,
    isLunar: true,
  },
  {
    day: '9/21',
    title: 'شهادت حضرت علی علیه السلام',
    holiday: true,
    isLunar: true,
  },
  { day: '9/22', title: 'شب قدر', holiday: true, isLunar: true },
  { day: '10/2', title: 'عید سعید فطر', holiday: true, isLunar: true },
  {
    day: '10/3',
    title: 'تعطیل به مناسبت عید سعید فطر',
    holiday: true,
    isLunar: true,
  },
  {
    day: '10/26',
    title: 'شهادت امام جعفر صادق علیه السلام',
    holiday: true,
    isLunar: true,
  },
  {
    day: '11/2',
    title: 'ولادت حضرت معصومه سلام الله علیها و روز دختران',
    holiday: false,
    isLunar: true,
  },
  {
    day: '11/12',
    title: 'ولادت امام رضا علیه السلام',
    holiday: false,
    isLunar: true,
  },
  {
    day: '11/30',
    title: 'شهادت امام محمد تقی علیه السلام',
    holiday: false,
    isLunar: true,
  },
  {
    day: '12/7',
    title: 'شهادت امام محمد باقرعلیه السلام',
    holiday: false,
    isLunar: true,
  },
  { day: '12/9', title: 'روز عرفه', holiday: false, isLunar: true },
  { day: '12/10', title: 'عید سعید قربان', holiday: true, isLunar: true },
  {
    day: '12/15',
    title: 'ولادت امام علی النقی الهادی علیه السلام',
    holiday: false,
    isLunar: true,
  },
  { day: '12/18', title: 'عید سعید غدیر خم', holiday: true, isLunar: true },
  {
    day: '12/20',
    title: 'ولادت امام موسی کاظم علیه السلام',
    holiday: false,
    isLunar: true,
  },
  { day: '1/10', title: 'تاسوعای حسینی', holiday: true, isLunar: true },
  { day: '1/11', title: 'عاشورای حسینی', holiday: true, isLunar: true },
  {
    day: '1/13',
    title: 'شهادت امام زین العابدین علیه السلام',
    holiday: false,
    isLunar: true,
  },
  {
    day: '1/14',
    title: 'شهادت امام زین العابدین علیه السلام',
    holiday: false,
    isLunar: true,
  },
  { day: '2/20', title: 'اربعین حسینی', holiday: true, isLunar: true },
  {
    day: '2/28',
    title: 'رحلت رسول اکرم؛شهادت امام حسن مجتبی علیه السلام',
    holiday: true,
    isLunar: true,
  },
  {
    day: '2/28',
    title: 'رحلت رسول اکرم؛شهادت امام حسن مجتبی علیه السلام',
    holiday: false,
    isLunar: true,
  },
  {
    day: '2/30',
    title: 'شهادت امام رضا علیه السلام',
    holiday: true,
    isLunar: true,
  },
  {
    day: '3/1',
    title: 'هجرت پیامبر اکرم از مکه به مدینه',
    holiday: false,
    isLunar: true,
  },
  {
    day: '3/9',
    title: 'شهادت امام حسن عسکری علیه السلام',
    holiday: true,
    isLunar: true,
  },
  {
    day: '3/13',
    title: 'میلاد رسول اکرم به روایت اهل سنت',
    holiday: false,
    isLunar: true,
  },
  {
    day: '3/18',
    title: 'میلاد رسول اکرم و امام جعفر صادق علیه السلام',
    holiday: true,
    isLunar: true,
  },
  {
    day: '4/11',
    title: 'وفات حضرت معصومه سلام الله علیها',
    holiday: false,
    isLunar: true,
  },
  {
    day: '5/6',
    title: 'ولادت حضرت زینب سلام الله علیها و روز پرستار و بهورز',
    holiday: false,
    isLunar: true,
  },
  {
    day: '6/4',
    title: 'شهادت حضرت فاطمه زهرا سلام الله علیها',
    holiday: true,
    isLunar: true,
  },
  {
    day: '6/21',
    title: 'ولادت حضرت فاطمه زهرا سلام الله علیها و روز زن',
    holiday: false,
    isLunar: true,
  },
  {
    day: '6/30',
    title: 'ولادت امام محمد باقر علیه السلام',
    holiday: false,
    isLunar: true,
  },
];
